### PR TITLE
Resolves some exceptions in VacolsService

### LINKED ISSUE #98: VACOLS is shown to be "Down" but VACOLS is functioning as expected
At https://monitor.cf.ds.va.gov/, the VACOLS box is shown to be "Down" but VACOLS is functioning as expected.

image

While this is not blocking any activity, it caused [some alarm with users](https://dsva.slack.com/archives/CHX8FMP28/p1593446399187400).

[Slack convo](https://dsva.slack.com/archives/CAM9FJ85P/p1593445522029800)

## AC
- [ ] VACOLS box shows actual status of VACOLS

### PR DESCRIPTION
**Pull request by ferristseng**
Resolves #98

Investigation notes are in the ticket

### CODE REVIEW

File: app/services/vacols_service.rb [hunk 1]
```diff
@@ -123,24 +122,36 @@ def update_datadog_metrics
     update_vacols_dd_metrics_exectime = Benchmark.realtime do
       @dog.batch_metrics do
         # wait time by class
-        @wait_time_by_class.each do |wtceach|
+        (@wait_time_by_class || []).each do |wtceach|
```
Comment (ferristseng) [inline app/services/vacols_service.rb:125]: If one of the queries fail in `query_service`, it's possible for some of these instance variables to be `nil`, which leads to this error: https://github.com/department-of-veterans-affairs/caseflow-monitor/issues/98#issuecomment-691230951.

File: app/services/vacols_service.rb [hunk 2]
```diff
@@ -123,24 +122,36 @@ def update_datadog_metrics
...
       end
     end
     Rails.logger.info("Vacols Service DD Exec Time took: %p" % update_vacols_dd_metrics_exectime)
   end
 
+  private
+
+  def should_reconnect_exception?(e)
+    lost_connection = e.cause.is_a?(OCIError) && LOST_CONNECTION_ERROR_CODES.include?(e.cause&.code)
+    closed_connection = e.cause.is_a?(OCIException) && e.message.include?("OCI8 was already closed.")
```
Comment (nanotone) [inline app/services/vacols_service.rb:153]: Yeah, this feels about right. OCIError defines the `#code` method, so this first line requires that specific subclass. Whereas the second line is a more generic check.

The safe-navigation on `e.cause&.code` means it'll probably still be correct if you only filter for OCIExceptions, though. So that'd be a place for a tiny bit of DRYing up, but it's just a matter of preference I think.

Comment (ferristseng) [reply app/services/vacols_service.rb:153]: > The safe-navigation on e.cause&.code means it'll probably still be correct if you only filter for OCIExceptions, though. So that'd be a place for a tiny bit of DRYing up, but it's just a matter of preference I think.

Good catch! I am all for being as concise as possible.

**Review by nanotone — APPROVED** [review]
The diff looks good to me, although I'm not familiar with this codebase or how it's deployed. Feel free to keep me looped in when we want to test this in UAT.
